---
- name: install tomcat server
  hosts: ansible_client
  become: true
  tasks:
    - name: install java
      apt:
        name: java
        state: latest
    - name: download tomcat package
      get_url:
        url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v.8.5.46/bin/apache-tomcat-8.5.46.tar.gz
        dest: /usr/local
    - name: extract tomcat package
      unarchive:
        src: /usr/local/apache-tomcat-8.5.46.tar.gz
        dest: /usr/local
        remote_src: yes
    - name: start tomcat services
      shell: nohup /usr/local/apache-tomcat-8.5.46/bin/startup.sh